# Generated by Django 5.1.3 on 2024-11-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_dt_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_choices',
            field=models.DateField(choices=[('AL', 'Alimentos'), ('EL', 'Eletrônicos'), ('FE', 'Ferramentas'), ('VE', 'Vestimentas')], max_length=2, verbose_name='Categoria do Proudto'),
        ),
    ]
