# Generated by Django 5.1.3 on 2024-11-19 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_product_dt_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dt_joined',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_choices',
            field=models.CharField(choices=[('AL', 'Alimentos'), ('EL', 'Eletrônicos'), ('FE', 'Ferramentas'), ('VE', 'Vestimentas')], max_length=2, verbose_name='Categoria do Produto'),
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('entered_at', models.DateField(verbose_name='Data de Entrada')),
                ('leaved_at', models.DateField(verbose_name='Data de Saida')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
