# Generated by Django 5.1.3 on 2024-11-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_rename_product_name_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='entered_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='leaved_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Saida'),
        ),
    ]
