# Generated by Django 5.1.3 on 2024-11-20 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_stockhistory_entered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
    ]
