# Generated by Django 5.1.3 on 2024-11-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseerSupplier',
            fields=[
                ('cnpj', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='CNPJ')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cellphone', models.FloatField(max_length=20, verbose_name='Telefone')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.CharField(max_length=120, verbose_name='E-mail')),
                ('supplier_category', models.CharField(choices=[('EL', 'Eletrônicos'), ('AL', 'Alimentos'), ('FE', 'Ferramentas'), ('RO', 'Roupas')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('cpf', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='CPF')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cellphone', models.FloatField(max_length=20, verbose_name='Telefone')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.CharField(max_length=120, verbose_name='E-mail')),
            ],
        ),
    ]
